### ISSUE TITLE
Unable to reproduce results on Coco with Retina-PVT small 640x

### ISSUE THREAD

**Issue by haithanhp** [whai362/PVT#10]
Hi @whai362,

Thanks for the very nice work. I trained your model with your instructions but I am unable to achieve your results of Retina small 640 on Coco: **38.7 AP**. Here is my results:

![PVT_retina_640_coco_results](https://user-images.githubusercontent.com/25809722/111020746-13799400-8396-11eb-8c84-340ad0159251.png)

Do you have any suggestions to reproduce your results on COCO? Thanks!!

**Comment by whai362** [comment]
Probably because PVT-based RetinaNet training is unstable
This is my training log: [Link](https://drive.google.com/file/d/1oJydUSU3D03geOSzNrlDnn5el0RMbOW9/view?usp=sharing)
Hope it can help you.
The instability of training may be caused by the padding zeros in the input image. We are trying to solve this problem latter.
