### ISSUE TITLE
how to train on single GPU?

### ISSUE THREAD

**Issue by Weifeng-Chen** [whai362/PVT#9]

**Comment by whai362** [comment]
You could try `sh dist_train.sh pvt_small 1 /path/to/checkpoint_root --data-path /path/to/imagenet`.
But I haven't trained models on a single GPU, so the performance is unclear.

**Comment by Weifeng-Chen** [comment]
OK thank you, I made it.
另外，请问可以提供一下 retinanet_pvt_s_fpn_1x_coco_640.pth 的其他下载渠道吗？（国内连接不了google drive）

**Comment by whai362** [comment]
ok, 我下次push的时候更新一下

**Comment by whai362** [comment]
链接: https://pan.baidu.com/s/1G4O7fa-Ogh0wn6cqNOUfTA  密码: ppuu

**Comment by Weifeng-Chen** [comment]
> retinanet_pvt_s_fpn_1x_coco_640.pth: 链接: https://pan.baidu.com/s/1G4O7fa-Ogh0wn6cqNOUfTA 密码: ppuu
> retinanet_pvt_s_fpn_1x_coco.pth: 链接: https://pan.baidu.com/s/1xGHAYBqogstNUL5b-3eHng 密码: 4buk

thanks

**Comment by SamMohel** [comment]
I'm interested in your code ... I tried to train code in a single GPU  on another dataset instead of imageNet by this command

`./dist_train.sh pvt_small 1 /path/checkpoint_root --data-path /path to images`

but got 

`usage: train.py [-h] [--work-dir WORK_DIR] [--resume-from RESUME_FROM]
               [--no-validate]
                [--gpus GPUS | --gpu-ids GPU_IDS [GPU_IDS ...]] [--seed SEED]
                [--deterministic] [--options OPTIONS [OPTIONS ...]]
                [--cfg-options CFG_OPTIONS [CFG_OPTIONS ...]]
                [--launcher {none,pytorch,slurm,mpi}]
                [--local_rank LOCAL_RANK]
                config
train.py: error: unrecognized arguments: /path/checkpoint_root --data-path /path to images
Traceback (most recent call last):
  File "/home/user/anaconda3/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/user/anaconda3/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/user/anaconda3/lib/python3.7/site-packages/torch/distributed/launch.py", line 260, in <module>
    main()
  File "/home/user/anaconda3/lib/python3.7/site-packages/torch/distributed/launch.py", line 256, in main
    cmd=cmd)
subprocess.CalledProcessError: Command '['/home/user/anaconda3/bin/python', '-u', './train.py', '--local_rank=0', 'pvt_small', '--launcher', 'pytorch', '/path/checkpoint_root', '--data-path', '/path to images']' returned non-zero exit status 2.`

does this error from using a single GPU or from the images itself?

**Comment by Weifeng-Chen** [comment]
> I'm interested in your code ... I tried to train code in a single GPU on another dataset instead of imageNet by this command
> 
> `./dist_train.sh pvt_small 1 /path/checkpoint_root --data-path /path to images`
> 
> but got
> 
> `usage: train.py [-h] [--work-dir WORK_DIR] [--resume-from RESUME_FROM] [--no-validate] [--gpus GPUS | --gpu-ids GPU_IDS [GPU_IDS ...]] [--seed SEED] [--deterministic] [--options OPTIONS [OPTIONS ...]] [--cfg-options CFG_OPTIONS [CFG_OPTIONS ...]] [--launcher {none,pytorch,slurm,mpi}] [--local_rank LOCAL_RANK] config train.py: error: unrecognized arguments: /path/checkpoint_root --data-path /path to images Traceback (most recent call last): File "/home/user/anaconda3/lib/python3.7/runpy.py", line 193, in _run_module_as_main "__main__", mod_spec) File "/home/user/anaconda3/lib/python3.7/runpy.py", line 85, in _run_code exec(code, run_globals) File "/home/user/anaconda3/lib/python3.7/site-packages/torch/distributed/launch.py", line 260, in <module> main() File "/home/user/anaconda3/lib/python3.7/site-packages/torch/distributed/launch.py", line 256, in main cmd=cmd) subprocess.CalledProcessError: Command '['/home/user/anaconda3/bin/python', '-u', './train.py', '--local_rank=0', 'pvt_small', '--launcher', 'pytorch', '/path/checkpoint_root', '--data-path', '/path to images']' returned non-zero exit status 2.`
> 
> does this error from using a single GPU or from the images itself?

I simply run `python train.py configs/retinanet_pvt_s_fpn_1x_coco_640.py `, and it worked well. you can refer to mmdetection for more details.

**Comment by SamMohel** [comment]
Thanks. it's Done.. but what is this command for `./dist_train.sh pvt_small 1 /path/checkpoint_root --data-path /path to images `. Is this for training also?

**Comment by Weifeng-Chen** [comment]
> Thanks. it's Done.. but what is this command for `./dist_train.sh pvt_small 1 /path/checkpoint_root --data-path /path to images `. Is this for training also?

you can open  `./dist_train.sh` to have a look. it has some setting about multi-GPU. I didn't try it.
